---
- name: Sync repositories and prepare for export
  hosts: ext_repository
  gather_facts: no
  become: yes

  tasks:

  - name: Check for rhel-7-server-rpms
    assert:
      that: "'rhel-7-server-rpms' in repos"
      fail_msg: "Repos must include rhel-7-server-rpms to maintain base OS"

  - name: Set release version
    command:
      argv:
      - subscription-manager
      - release
      - --set={{ release_version }}

  - name: Install prereqs
    yum:
      name: "{{ item }}"
      state: present
    loop:
    - createrepo
    - deltarpm
    - yum-utils

  - name: Enable repositories
    command:
      argv:
      - subscription-manager
      - repos
      - --enable={{ item }}
    loop: "{{ repos }}"

  - name: Sync the repositories
    command:
      argv:
      - reposync
      - "{% if cleanup | default(false) %}--delete{% endif %}"
      - --downloadcomps
      - --download-metadata
      - --gpgcheck
      - "{% if newest | default(false) %}--newest-only{% endif %}"
      - --plugins
      - --repoid={{ item }}
      - --download_path={{ repo_path }}
    loop: "{{ repos }}"

  - name: Create/update repositories
    command:
      argv:
      - createrepo
      - --groupfile
      - comps.xml
      - --quiet
      - --update
      - "{{ repo_path }}/{{ item }}"
      chdir: "{{ repo_path }}/{{ item }}"
    loop: "{{ repos }}"

  - name: Tar repos for export
    archive:
      path: "{{ repo_path }}/{{ item }}"
      dest: "{{ output_path }}/{{ item }}.tgz"
    loop: "{{ repos }}"
